/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utilitarios.Curso;
import utilitarios.CursoDAO;
import utilitarios.Disciplinas;
import utilitarios.Professor;
import utilitarios.ProfessorDAO;
import utilitarios.DisciplinasDAO;
import utilitarios.Periodo;
import utilitarios.PeriodoDAO;

/**
 *
 * @author Diego
 */
public class EditarPrefCurso extends javax.swing.JFrame {

    /**
     * Creates new form EditarPrefCurso
     */
    Curso curso;
    CursoDAO cursoDAO = new CursoDAO();
    DisciplinasDAO disciplinasDAO = new DisciplinasDAO();
    Periodo periodo = new Periodo();
    PeriodoDAO perDao = new PeriodoDAO();
    ArrayList<Periodo> Aperiodo= new ArrayList<Periodo>();
    ArrayList<Disciplinas> disciplinasDocurso = new ArrayList<Disciplinas>();
    ArrayList<Disciplinas> disciplinasdisponiveis = new ArrayList<Disciplinas>();
    
    @SuppressWarnings("empty-statement")
    public EditarPrefCurso() {
        initComponents();
        
        
        //System.out.println("eita "+curso.getNome()+curso.getTurno()+curso.getNumPeriodos());
        
        
        
        disciplinasdisponiveis=disciplinasDAO.listar();
        DefaultTableModel modelo = new DefaultTableModel(); 
        modelo=(DefaultTableModel) jTDisciplinasDispo.getModel();
        int i=0;
        Disciplinas disp = new Disciplinas();

        while(i<disciplinasdisponiveis.size())
        {
            disp=disciplinasdisponiveis.get(i);
            modelo.addRow(new Object[]{disp.getNome(),disp.getCargaHoraria()});
            i++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTFnomeCurso = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboTurno = new javax.swing.JComboBox<String>();
        jComboNPeriodo = new javax.swing.JComboBox<String>();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTDisciplinasVinc = new javax.swing.JTable();
        jBexcluirDisciplina = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jComboPeriodo = new javax.swing.JComboBox<String>();
        jBSalvarPeriodo = new javax.swing.JButton();
        jBvoltar = new javax.swing.JButton();
        jSalvar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTDisciplinasDispo = new javax.swing.JTable();
        jBaddDispCurso = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Adicionar Curso");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações do Curso"));

        jLabel1.setText("Nome do Curso:");

        jLabel2.setText("Turno:");

        jComboTurno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Matutino", "Vespertino", "Noturno", "Integral" }));

        jComboNPeriodo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jComboNPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboNPeriodoActionPerformed(evt);
            }
        });

        jLabel3.setText("Numero de Periodos:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTFnomeCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jComboTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jComboNPeriodo, 0, 46, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFnomeCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jComboTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jComboNPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações do Curso"));

        jTDisciplinasVinc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Disciplinas Vinculadas ao Curso", "Carga Horária"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTDisciplinasVinc);
        if (jTDisciplinasVinc.getColumnModel().getColumnCount() > 0) {
            jTDisciplinasVinc.getColumnModel().getColumn(0).setPreferredWidth(250);
        }

        jBexcluirDisciplina.setText("Excluir Disciplina da Tabela");
        jBexcluirDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBexcluirDisciplinaActionPerformed(evt);
            }
        });

        jLabel4.setText("Periodo:");

        jComboPeriodo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1" }));
        jComboPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboPeriodoActionPerformed(evt);
            }
        });

        jBSalvarPeriodo.setText("Salvar Período");
        jBSalvarPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalvarPeriodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jComboPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jBexcluirDisciplina)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBSalvarPeriodo)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBexcluirDisciplina)
                    .addComponent(jBSalvarPeriodo))
                .addContainerGap())
        );

        jBvoltar.setText("Voltar");
        jBvoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBvoltarActionPerformed(evt);
            }
        });

        jSalvar.setText("Salvar Modificações");
        jSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalvarActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Disciplinas Disponiveis"));

        jTDisciplinasDispo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Disciplinas Disponiveis", "Carga Horária"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTDisciplinasDispo);
        if (jTDisciplinasDispo.getColumnModel().getColumnCount() > 0) {
            jTDisciplinasDispo.getColumnModel().getColumn(0).setPreferredWidth(250);
        }

        jBaddDispCurso.setText("Adicionar Disciplina ao Curso");
        jBaddDispCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBaddDispCursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBaddDispCurso))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBaddDispCurso)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBvoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSalvar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBvoltar)
                    .addComponent(jSalvar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void passarCurso(String nomeCurso){
        jTFnomeCurso.setText(nomeCurso);
    }
    
    private void jBvoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBvoltarActionPerformed
        TelaPrincipal tp = new TelaPrincipal();
        tp.setDefaultCloseOperation(EXIT_ON_CLOSE);
        tp.setLocationRelativeTo(this);
        tp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBvoltarActionPerformed

    private void jBexcluirDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBexcluirDisciplinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBexcluirDisciplinaActionPerformed

    private void jSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalvarActionPerformed
        
        Curso curso = new Curso();
        Professor professor = new Professor();
        ProfessorDAO professorDAO = new ProfessorDAO();
        boolean existente;
        
        if(jTFnomeCurso.getText().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Nome do curso invalido!", "Erro", JOptionPane.WARNING_MESSAGE);
        }
        
        else
        {
            curso.setNome(jTFnomeCurso.getText());
            curso.setTurno((String) jComboTurno.getSelectedItem());
            professor.setCod(professorDAO.buscar_Ativo());
            existente=cursoDAO.buscar_Repeticao(curso);
            
            if(existente==false)
            {
                curso.setProfCoord(professor.getCod());
                cursoDAO.inserir(curso);
                this.curso.setCod(cursoDAO.buscarCodCurso(curso));
            }
            
            else
            {
                JOptionPane.showMessageDialog(rootPane, "Curso existente", "Erro", JOptionPane.INFORMATION_MESSAGE);
            } 
        }
    }//GEN-LAST:event_jSalvarActionPerformed

    private void jBaddDispCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBaddDispCursoActionPerformed
        
        DefaultTableModel modelo = new DefaultTableModel(); 
        modelo=(DefaultTableModel) jTDisciplinasVinc.getModel();
        
        Disciplinas disciplina = new Disciplinas();
        
        disciplina.setNome((String) jTDisciplinasDispo.getValueAt(jTDisciplinasDispo.getSelectedRow(), 0));
        disciplina.setCargaHoraria((int) jTDisciplinasDispo.getValueAt(jTDisciplinasDispo.getSelectedRow(), 1));
       
        modelo.addRow(new Object[]{disciplina.getNome(),disciplina.getCargaHoraria()});
      
    }//GEN-LAST:event_jBaddDispCursoActionPerformed

    private void jComboPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboPeriodoActionPerformed
        
    }//GEN-LAST:event_jComboPeriodoActionPerformed

    private void jComboNPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboNPeriodoActionPerformed
        int num=Integer.parseInt(String.valueOf(jComboNPeriodo.getSelectedItem()));
        
        jComboPeriodo.removeAllItems();
        for(int i=1;i<=num;i++)
        {
            jComboPeriodo.addItem(String.valueOf(i));
        }
    }//GEN-LAST:event_jComboNPeriodoActionPerformed

    private void jBSalvarPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalvarPeriodoActionPerformed
        ArrayList<Periodo> aPer = new ArrayList();
        
        if(jTDisciplinasVinc.getRowCount()!=0){
            for(int i = 0; i<jTDisciplinasVinc.getRowCount();i++){
                aPer.add(new Periodo(Integer.parseInt(String.valueOf(jComboPeriodo.getSelectedItem())),
                        disciplinasDAO.buscar(new Disciplinas(String.valueOf(jTDisciplinasVinc.getValueAt(i, 0)),
                                Integer.parseInt(String.valueOf(jTDisciplinasVinc.getValueAt(i, 1)))))));
                
                perDao.inserir(aPer.get(i));
            }
        }
    }//GEN-LAST:event_jBSalvarPeriodoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarPrefCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarPrefCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarPrefCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarPrefCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarPrefCurso().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBSalvarPeriodo;
    private javax.swing.JButton jBaddDispCurso;
    private javax.swing.JButton jBexcluirDisciplina;
    private javax.swing.JButton jBvoltar;
    private javax.swing.JComboBox<String> jComboNPeriodo;
    private javax.swing.JComboBox<String> jComboPeriodo;
    private javax.swing.JComboBox<String> jComboTurno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jSalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTDisciplinasDispo;
    private javax.swing.JTable jTDisciplinasVinc;
    private javax.swing.JTextField jTFnomeCurso;
    // End of variables declaration//GEN-END:variables
}
