package gui;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import utilitarios.AreaAtuacao;
import utilitarios.AreaAtuacaoDAO;
import utilitarios.Criptografia;
import utilitarios.Perguntas;
import utilitarios.PerguntasDAO;
import utilitarios.Professor;
import utilitarios.ProfessorDAO;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Classe responsável pela implementação da tela de login.
 * @author Tarcísio
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btEntrar = new javax.swing.JButton();
        btCadastro = new javax.swing.JButton();
        tfUsuario = new javax.swing.JTextField();
        pfSenha = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbErroLogin = new javax.swing.JLabel();
        jBEsqueci = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnSobre = new javax.swing.JMenuItem();
        mnSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SisCoor: Módulo Horário de Aulas");
        setResizable(false);

        jLabel1.setText("Usuário:");

        jLabel2.setText("Senha:");

        btEntrar.setMnemonic('e');
        btEntrar.setText("Entrar");
        btEntrar.setToolTipText("Clique aqui para entrar!");
        btEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEntrarActionPerformed(evt);
            }
        });

        btCadastro.setMnemonic('c');
        btCadastro.setText("Cadastro");
        btCadastro.setToolTipText("Clique aqui para se cadastrar.");
        btCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastroActionPerformed(evt);
            }
        });

        tfUsuario.setToolTipText("Entre com o \"Usuário\" aqui!");
        tfUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfUsuarioFocusGained(evt);
            }
        });
        tfUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfUsuarioKeyPressed(evt);
            }
        });

        pfSenha.setToolTipText("Entre com sua senha aqui!");
        pfSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pfSenhaFocusGained(evt);
            }
        });
        pfSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pfSenhaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pfSenhaKeyTyped(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/lock-icon.png"))); // NOI18N
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("SisCoor - Módulo Horário de Aulas");

        lbErroLogin.setForeground(new java.awt.Color(204, 0, 0));

        jBEsqueci.setMnemonic('s');
        jBEsqueci.setText("Esqueci minha senha");
        jBEsqueci.setToolTipText("Recupere sua senha aqui.");
        jBEsqueci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEsqueciActionPerformed(evt);
            }
        });

        jMenu1.setText("Sistema");

        mnSobre.setText("Sobre");
        mnSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSobreActionPerformed(evt);
            }
        });
        jMenu1.add(mnSobre);

        mnSair.setText("Sair");
        mnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSairActionPerformed(evt);
            }
        });
        jMenu1.add(mnSair);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btCadastro)
                                .addGap(18, 18, 18)
                                .addComponent(jBEsqueci)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addComponent(btEntrar)
                                .addGap(5, 5, 5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(pfSenha)
                                    .addComponent(tfUsuario))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbErroLogin))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel4)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(lbErroLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEntrar)
                    .addComponent(btCadastro)
                    .addComponent(jBEsqueci))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfUsuarioKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            lbErroLogin.setText("Digite sua senha!");
        }
    }//GEN-LAST:event_tfUsuarioKeyPressed

    private void btEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEntrarActionPerformed
        boolean encontrou = false;
        
        ProfessorDAO prof = new ProfessorDAO();
        prof.desativar_Professor();
        
        if(tfUsuario.getText().isEmpty()||String.valueOf(pfSenha.getPassword()).isEmpty()){
            lbErroLogin.setText("Insira usuário e senha!");
            pfSenha.setText("");
        }else{
            ArrayList<Professor> profs = new ArrayList<Professor>();
            ProfessorDAO profBD = new ProfessorDAO();
            
            profs = profBD.listar();

            for(int i = 0; i<profs.size();i++){
                if(tfUsuario.getText().equals(profs.get(i).getUsername())&&Criptografia.criptografar(String.valueOf(pfSenha.getPassword())).equals(profs.get(i).getSenha())){
                    JOptionPane.showMessageDialog(this, "Bem vindo!", "Boas vindas", HEIGHT);
                    encontrou = true;
                    profBD.ativar_Professor(tfUsuario.getText());
                }

                if((i+1)==profs.size()&&encontrou==false){
                     JOptionPane.showMessageDialog(this, "Usuário e/ou senha incorreto!", "Erro!", HEIGHT);
                     pfSenha.setText("");
                }
            }
        }
    }//GEN-LAST:event_btEntrarActionPerformed

    private void tfUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfUsuarioFocusGained
        lbErroLogin.setText("");
    }//GEN-LAST:event_tfUsuarioFocusGained

    private void pfSenhaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pfSenhaKeyTyped
        if(!lbErroLogin.getText().isEmpty()){
            lbErroLogin.setText("");
        }
    }//GEN-LAST:event_pfSenhaKeyTyped

    private void pfSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pfSenhaKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            btEntrarActionPerformed(null);
        }
    }//GEN-LAST:event_pfSenhaKeyPressed

    private void btCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastroActionPerformed
        AreaAtuacaoDAO area = new AreaAtuacaoDAO();
        PerguntasDAO perg = new PerguntasDAO();
        ArrayList<AreaAtuacao> aArea = area.listar();
        ArrayList<Perguntas> aPerg = perg.listar();
        
        TelaCadastro tc = new TelaCadastro();
        tc.setDefaultCloseOperation(HIDE_ON_CLOSE);
        tc.setLocationRelativeTo(null);
        tc.setVisible(true);
        
        for(int i=0;i<aArea.size();i++){
            tc.addItem(aArea.get(i).getNomeArea());
        }
        
        for(int i=0;i<aPerg.size();i++){
            tc.addItemP(aPerg.get(i).getPergunta());
        }
        
        Calendar cal = GregorianCalendar.getInstance();
        
        for(int i = 1940;i<=cal.get(Calendar.YEAR);i++){
            tc.addItemAno(i);
            if(i == Calendar.YEAR){
                break;
            }
        }
    }//GEN-LAST:event_btCadastroActionPerformed

    private void pfSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pfSenhaFocusGained
        lbErroLogin.setText("");
    }//GEN-LAST:event_pfSenhaFocusGained

    private void mnSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSobreActionPerformed
        JOptionPane.showMessageDialog(this,"Sistema de Coordenadoria - SisCoor\nCriado por: Diego, Tarcisio e Filipe\nSetembro de 2016");
    }//GEN-LAST:event_mnSobreActionPerformed

    private void mnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnSairActionPerformed

    private void jBEsqueciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEsqueciActionPerformed
        
        PerguntasDAO perg = new PerguntasDAO();
        ArrayList<Perguntas> aPerg = perg.listar();
        
        EsqueciSenha es = new EsqueciSenha();
        es.setDefaultCloseOperation(HIDE_ON_CLOSE);
        es.setLocationRelativeTo(null);
        es.setVisible(true);

        
        for(int i=0;i<aPerg.size();i++){
            es.addItem(aPerg.get(i).getPergunta());
        }
        Calendar cal = GregorianCalendar.getInstance();
        
        for(int i = 1940;i<=cal.get(Calendar.YEAR);i++){
            es.addItemAno(i);
            if(i == Calendar.YEAR){
                break;
            }
        }
    }//GEN-LAST:event_jBEsqueciActionPerformed

public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visualizar_restricao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visualizar_restricao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visualizar_restricao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visualizar_restricao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastro;
    private javax.swing.JButton btEntrar;
    private javax.swing.JButton jBEsqueci;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbErroLogin;
    private javax.swing.JMenuItem mnSair;
    private javax.swing.JMenuItem mnSobre;
    private javax.swing.JPasswordField pfSenha;
    private javax.swing.JTextField tfUsuario;
    // End of variables declaration//GEN-END:variables
}
