/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.ArrayList;
import utilitarios.AreaAtuacao;
import utilitarios.AreaAtuacaoDAO;
import utilitarios.Professor;
import utilitarios.ProfessorDAO;

/**
 *
 * @author livre
 */
public class TelaPrincipal extends javax.swing.JFrame {
    Professor prof = ProfessorDAO.buscarProfAtivo();
    
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuMinhaConta = new javax.swing.JMenu();
        menuInfoPessoal = new javax.swing.JMenuItem();
        menuRestricao = new javax.swing.JMenu();
        menuAddRestricao = new javax.swing.JMenuItem();
        menuEditarRestricao = new javax.swing.JMenuItem();
        menuExcluirRestricao = new javax.swing.JMenuItem();
        menuVisualizarRestricao = new javax.swing.JMenuItem();
        menuLogoff = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuMinhaConta.setText("Minha Conta");

        menuInfoPessoal.setText("Editar Informações Pessoais");
        menuInfoPessoal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInfoPessoalActionPerformed(evt);
            }
        });
        menuMinhaConta.add(menuInfoPessoal);

        menuRestricao.setText("Restrições");

        menuAddRestricao.setText("Adicionar Restrição");
        menuAddRestricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddRestricaoActionPerformed(evt);
            }
        });
        menuRestricao.add(menuAddRestricao);

        menuEditarRestricao.setText("Editar Restrição");
        menuEditarRestricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditarRestricaoActionPerformed(evt);
            }
        });
        menuRestricao.add(menuEditarRestricao);

        menuExcluirRestricao.setText("Excluir Restrição");
        menuExcluirRestricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExcluirRestricaoActionPerformed(evt);
            }
        });
        menuRestricao.add(menuExcluirRestricao);

        menuVisualizarRestricao.setText("Visualizar Restrições");
        menuVisualizarRestricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVisualizarRestricaoActionPerformed(evt);
            }
        });
        menuRestricao.add(menuVisualizarRestricao);

        menuMinhaConta.add(menuRestricao);

        menuLogoff.setText("Desconectar");
        menuLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogoffActionPerformed(evt);
            }
        });
        menuMinhaConta.add(menuLogoff);

        jMenuBar1.add(menuMinhaConta);

        jMenu2.setText("Ajuda");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void menuInfoPessoalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInfoPessoalActionPerformed
        ArrayList<AreaAtuacao> aArea = AreaAtuacaoDAO.listar();
        EditarInformacoesPessoais eip = new EditarInformacoesPessoais(this.prof);
        eip.setLocationRelativeTo(this);
        eip.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        eip.setVisible(true);
        
        eip.addItem("Outro(a)");
        for(int i=0;i<aArea.size();i++){
            eip.addItem(aArea.get(i).getNomeArea());
        }
        
    }//GEN-LAST:event_menuInfoPessoalActionPerformed

    private void menuAddRestricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddRestricaoActionPerformed
        NovaRestricao nr = new NovaRestricao();
        nr.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        nr.setLocationRelativeTo(this);
        nr.setVisible(true);
    }//GEN-LAST:event_menuAddRestricaoActionPerformed

    private void menuEditarRestricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditarRestricaoActionPerformed
        EditarRestricao er = new EditarRestricao();
        
        er.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        er.setLocationRelativeTo(this);
        er.setVisible(true);
    }//GEN-LAST:event_menuEditarRestricaoActionPerformed

    private void menuExcluirRestricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExcluirRestricaoActionPerformed
        DeletarRestricao dr = new DeletarRestricao();
        
        dr.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        dr.setLocationRelativeTo(this);
        dr.setVisible(true);
    }//GEN-LAST:event_menuExcluirRestricaoActionPerformed

    private void menuVisualizarRestricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVisualizarRestricaoActionPerformed
        VisualizarRestricao vr = new VisualizarRestricao();
        
        vr.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        vr.setLocationRelativeTo(this);
        vr.setVisible(true);
    }//GEN-LAST:event_menuVisualizarRestricaoActionPerformed

    private void menuLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogoffActionPerformed
        ProfessorDAO profD = new ProfessorDAO();
        
        profD.desativar_Professor();
        
        TelaLogin tl = new TelaLogin();
        tl.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        tl.setLocationRelativeTo(this);
        tl.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_menuLogoffActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuAddRestricao;
    private javax.swing.JMenuItem menuEditarRestricao;
    private javax.swing.JMenuItem menuExcluirRestricao;
    private javax.swing.JMenuItem menuInfoPessoal;
    private javax.swing.JMenuItem menuLogoff;
    private javax.swing.JMenu menuMinhaConta;
    private javax.swing.JMenu menuRestricao;
    private javax.swing.JMenuItem menuVisualizarRestricao;
    // End of variables declaration//GEN-END:variables
}
