/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.security.MessageDigest;
import java.util.ArrayList;
import utilitarios.AreaAtuacao;
import utilitarios.AreaAtuacaoDAO;
import utilitarios.Criptografia;
import utilitarios.Professor;
import utilitarios.ProfessorDAO;

/**
 *
 * @author Tarcisio
 */
public class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfNomeCad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfEmailCad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfUsernameCad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        comboAreaAtuacao = new javax.swing.JComboBox();
        tfAreaAtuacao = new javax.swing.JTextField();
        btVoltar = new javax.swing.JButton();
        btCad = new javax.swing.JButton();
        pfSenhaCad = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        lbErro = new javax.swing.JLabel();
        pfSenhaRep = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        lbCadastroArea = new javax.swing.JLabel();

        jLabel7.setText("Senha:");

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/cats.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Cadastre-se:");

        jLabel2.setText("Nome Completo:");

        tfNomeCad.setToolTipText("Entre com seu nome completo.");

        jLabel4.setText("E-mail:");

        tfEmailCad.setToolTipText("Entre com um e-mail válido.");

        jLabel5.setText("Usuário:");

        tfUsernameCad.setToolTipText("Mínimo de 6 dígitos.");

        jLabel6.setText("Senha:");

        jLabel8.setText("Área de Atuação:");

        comboAreaAtuacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Outro(a)" }));
        comboAreaAtuacao.setToolTipText("Caso sua área não esteja listada aqui, crie uma selecionando \"Outro(a)\".");
        comboAreaAtuacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAreaAtuacaoActionPerformed(evt);
            }
        });

        tfAreaAtuacao.setEditable(false);
        tfAreaAtuacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAreaAtuacaoActionPerformed(evt);
            }
        });

        btVoltar.setMnemonic('V');
        btVoltar.setText("Voltar");
        btVoltar.setToolTipText("Voltar à tela de login.");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        btCad.setMnemonic('c');
        btCad.setText("Cadastrar");
        btCad.setToolTipText("Cadastrar novo(a) usuário(a) e/ou área de atuação.");
        btCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadActionPerformed(evt);
            }
        });

        pfSenhaCad.setToolTipText("Mínimo de 6 dígitos.");

        jLabel9.setText("Obs.: Todos os campos são obrigatórios!");

        lbErro.setForeground(new java.awt.Color(250, 0, 0));

        jLabel10.setText("Repita sua Senha:");

        lbCadastroArea.setForeground(new java.awt.Color(0, 0, 250));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(134, 134, 134))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbErro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNomeCad)
                            .addComponent(tfEmailCad)
                            .addComponent(tfUsernameCad, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pfSenhaCad)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(btVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                        .addComponent(btCad)
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboAreaAtuacao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pfSenhaRep)
                            .addComponent(tfAreaAtuacao)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lbCadastroArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNomeCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfEmailCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfUsernameCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(pfSenhaCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(pfSenhaRep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(comboAreaAtuacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfAreaAtuacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btVoltar)
                    .addComponent(btCad))
                .addGap(19, 19, 19)
                .addComponent(lbCadastroArea)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbErro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void tfAreaAtuacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAreaAtuacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAreaAtuacaoActionPerformed

    public void addItem(String nomeItem) {
        comboAreaAtuacao.addItem(nomeItem);
    }

    private void btCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadActionPerformed
        lbCadastroArea.setText("");
        lbErro.setText("");
        
        Professor prof = new Professor();
        AreaAtuacao aa = new AreaAtuacao();
        ProfessorDAO pf = new ProfessorDAO();
        AreaAtuacaoDAO area = new AreaAtuacaoDAO();
        ArrayList<Professor> aProf = pf.listar();
        ArrayList<AreaAtuacao> aArea = area.listar();
        int areaAtuacao;
        boolean encontrou = false;
        boolean erroSenha = false;
        boolean erroEmail = false;
        boolean erroArea = false;
        boolean erroSenhaRep = false;
        boolean erroAreaRep = false;
        boolean deveInserir = true;

        if (tfNomeCad.getText().isEmpty() || tfEmailCad.getText().isEmpty() || tfEmailCad.getText().isEmpty() || String.valueOf(pfSenhaCad.getPassword()).isEmpty() || String.valueOf(pfSenhaRep.getPassword()).isEmpty()) {
            lbErro.setText("Preencha todos os campos!");
            pfSenhaCad.setText("");
            pfSenhaRep.setText("");
        }

        for (int i = 0; i < aProf.size(); i++) {
            if (tfEmailCad.getText().equals(aProf.get(i).getEmail()) && !tfEmailCad.getText().equals(aProf.get(i).getEmail())) {
                lbErro.setText("Usuário já cadastrado! Tente novamente");
                tfUsernameCad.setText("");
                encontrou = true;
                break;
            } else if (tfEmailCad.getText().equals(aProf.get(i).getEmail()) && !tfUsernameCad.getText().equals(aProf.get(i).getUsername())) {
                lbErro.setText("E-mail já cadastrado! Tente novamente");
                tfEmailCad.setText("");
                encontrou = true;
                break;
            } else if (tfUsernameCad.getText().equals(aProf.get(i).getUsername()) && tfEmailCad.getText().equals(aProf.get(i).getEmail())) {
                lbErro.setText("Usuário e e-mail já cadastrados! Tente novamente");
                tfEmailCad.setText("");
                tfUsernameCad.setText("");
                encontrou = true;
                break;
            }
            lbErro.setText("");
        }

        if (encontrou == false) {
            if (String.valueOf(pfSenhaCad.getPassword()).length() < 6 && !(tfUsernameCad.getText().length() < 6)) {
                lbErro.setText("Campo 'Senha' deve conter 6 dígitos alfanuméricos ou mais!");
                pfSenhaCad.setText("");
                pfSenhaRep.setText("");
                erroSenha = true;
            } else if (tfUsernameCad.getText().length() < 6 && !(String.valueOf(pfSenhaCad.getPassword()).length() < 6)) {
                lbErro.setText("Campo 'Usuário' deve conter 6 dígitos alfanuméricos ou mais!");
                pfSenhaCad.setText("");
                pfSenhaRep.setText("");
                erroSenha = true;
            } else if (tfUsernameCad.getText().length() < 6 && String.valueOf(pfSenhaCad.getPassword()).length() < 6) {
                lbErro.setText("Campos 'Usuário' e 'Senha' devem conter 6 dígitos alfanuméricos ou mais!");
                pfSenhaCad.setText("");
                pfSenhaRep.setText("");
                erroSenha = true;
            } else {
                lbErro.setText("");
                erroSenha = false;
            }

            if (erroSenha == false) {
                if (tfEmailCad.getText().indexOf('@') == -1 || tfEmailCad.getText().indexOf('.') == -1) {
                    lbErro.setText("Digite um E-mail válido!");
                    pfSenhaCad.setText("");
                    pfSenhaRep.setText("");
                    erroEmail = true;
                } else {
                    lbErro.setText("");
                    erroEmail = false;
                }

                if (erroEmail == false) {
                    if (comboAreaAtuacao.getSelectedItem().equals("Outro(a)") && tfAreaAtuacao.getText().isEmpty()) {
                        lbErro.setText("Digite sua area de atuação!");
                        pfSenhaCad.setText("");
                        pfSenhaRep.setText("");
                        erroArea = true;
                    } else {
                        lbErro.setText("");
                        erroArea = false;
                    }

                    if (erroArea == false) {
                        if (!String.valueOf(pfSenhaCad.getPassword()).equals(String.valueOf(pfSenhaRep.getPassword()))) {
                            lbErro.setText("As senhas não conferem!");
                            pfSenhaCad.setText("");
                            pfSenhaRep.setText("");
                            erroSenhaRep = true;
                        } else {
                            lbErro.setText("");
                            erroSenhaRep = false;
                        }
                        
                        if(comboAreaAtuacao.getSelectedItem().equals("Outro(a)")) {
                            for(int i=0; i < aArea.size(); i++){
                                if(tfAreaAtuacao.getText().equals(aArea.get(i).getNomeArea())){
                                    lbErro.setText("Área já cadastrada!");
                                    comboAreaAtuacao.setSelectedItem(aArea.get(i).getNomeArea());
                                    tfAreaAtuacao.setText("");
                                    tfAreaAtuacao.setEditable(false);
                                    erroAreaRep = true;
                                    break;
                                }
                            }
                            
                            if(erroAreaRep==false){
                                aa.setNomeArea(tfAreaAtuacao.getText());
                                area.inserir(aa);
                                addItem(aa.getNomeArea());
                                comboAreaAtuacao.setSelectedItem(aa.getNomeArea());
                                tfAreaAtuacao.setText("");
                                deveInserir = false;
                                btCadActionPerformed(evt);
                            }
                        }
                    }
                }
        }

        if (encontrou == false && erroArea == false && erroEmail == false && erroSenha == false && erroSenhaRep == false && erroAreaRep == false&&deveInserir == true) {
            String senhaC = String.valueOf(pfSenhaCad.getPassword());
            
            aArea = area.listar();
            
            for (int i = 0; i < aArea.size(); i++) {
                if (comboAreaAtuacao.getSelectedItem().equals(aArea.get(i).getNomeArea())) {
                    prof.setAreaAtuacao(aArea.get(i).getCod());
                    break;
                }
            }

            prof.setNome(tfNomeCad.getText());
            prof.setUsername(tfUsernameCad.getText());
            prof.setEmail(tfEmailCad.getText());
            prof.setSenha(Criptografia.criptografar(senhaC));
            pf.inserir(prof);
            
            lbCadastroArea.setText("Cadastro realizado com sucesso!");
        }
        }
    }//GEN-LAST:event_btCadActionPerformed

    private void comboAreaAtuacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAreaAtuacaoActionPerformed
        if (comboAreaAtuacao.getSelectedItem().equals("Outro(a)")) {
            tfAreaAtuacao.setEditable(true);
        } else {
            tfAreaAtuacao.setEditable(false);
        }
    }//GEN-LAST:event_comboAreaAtuacaoActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btVoltarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCad;
    private javax.swing.JButton btVoltar;
    private javax.swing.JComboBox comboAreaAtuacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel lbCadastroArea;
    private javax.swing.JLabel lbErro;
    private javax.swing.JPasswordField pfSenhaCad;
    private javax.swing.JPasswordField pfSenhaRep;
    private javax.swing.JTextField tfAreaAtuacao;
    private javax.swing.JTextField tfEmailCad;
    private javax.swing.JTextField tfNomeCad;
    private javax.swing.JTextField tfUsernameCad;
    // End of variables declaration//GEN-END:variables
}
